### DISCUSSION TITLE
Swup is not animating: dependency bundling

### DISCUSSION THREAD

**Discussion by DylanDevelops** [swup/swup#514] [Help] [answered]
Swup is not working for me and I'm not sure why. I believe I have everything correct.

How I transition pages: (is having the ./ in the beginning fine with swup?)
```html
<a href="./about">
    <img src="./Images/arrow.png" alt="Learn More">
</a>
```
How I have the ID for all the pages: (The button that transitions between pages is within this main tag but I don't know if that means anything)
```html
<main id="swup" class="transition-fade">
```

The CSS:
```css

.transition-fade {
    transition: 0.4s;
    opacity: 1;
}

html.is-animating .transition-fade {
    opacity: 0;
}
```

If you guys need more info let me know but I think this is all that is needed to make stuff animate.
