### DISCUSSION TITLE
Reveal animation gradient with Parallel Plugin in Safari

### DISCUSSION THREAD

**Discussion by possible-is** [swup/swup#948] [Help]
### Describe your problem 🧐

Hello to all.

It appears that the gradient reveal transition is not working in Safari. I have tested it on Mac OS X (14.5) with Safari 17.5 and on my iPhone. 

Since it does not work on the demo page already (https://swup.js.org/getting-started/demos/) i can rule out some false implementation... 

### What is your question? 🙋‍♀️

Do you have any idea, why this particular transition isn't working in Safari? The Reveal Circle and Reveal Square Transition works fine in contrast. The gradient transition though just switches from one page to the other, without any animation whatsoever.

Any help is appreciated, because i think this is a very beautiful transition... :)

Greetings,
Matthias

### URL to minimal reproduction 🔗

https://swup.js.org/getting-started/demos/

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for answers to my question
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
You're correct, it doesn't work in Safari out of the box unfortunately. There might be some combination of prefixing or css that will work in Safari. If you do find it, feel free to post it here so we can update the demo!

**Comment by possible-is** [comment]
Thanks, @daun.

Unfortunately my skills are not sufficient to really find out what the problem might be.

In the meantime i switched to the "Overlay animation", which is just slightly less impressive than the Reveal gradient :)

I noticed a little bug in your demo though: If you go to the replit repository, there is this line missing in the next.html:
```html
<div class="overlay transition-overlay"></div> 
```
just before the </body> tag.
This causes the whole animation not to work once you landed on next.html instead of index.html
Maybe this is my little contribution to your wonderful tool!
Greetings,
Matthias

p.s. if someone ever fixes the gradient / Safari problem, please let me know!

**Reply by daun** [reply]
Thanks for the pointer! You're right about the missing overlay div. We'll update the demo as soon as possible.

**Comment by daun** [comment]
@possible-is I've given this another stab and gotten it to work in Safari. See [the updated demo](https://swup-demo-reveal-temp.replit.app/). The only catch: it seems to work for the first two transitions and then stops working, at least in Safari. Some more investigating to do, but at least we know the animation works in Safari :)

```css
html.is-changing .transition-reveal {
  transition: clip-path 1s cubic-bezier(0.5, 0, 0.15, 1), mask-position 1s cubic-bezier(0.5, 0, 0.15, 1);
  transition: clip-path 1s cubic-bezier(0.5, 0, 0.15, 1), -webkit-mask-position 1s cubic-bezier(0.5, 0, 0.15, 1);
}

.transition-reveal {
  mask-image: linear-gradient(to left, transparent 33.33%, white 66.66%);
  mask-size: 300% 100%;
  mask-position: 0%;
  -webkit-mask-image: linear-gradient(to left, transparent 33.33%, white 66.66%);
  -webkit-mask-size: 300% 100%;
  -webkit-mask-position: 0%;
}

.transition-reveal + .transition-reveal {
  mask-position: 100%;
  -webkit-mask-position: 100%;
}
```
