### ISSUE TITLE
JQuery script does not work with transition 

### ISSUE THREAD

**Issue by ModzDev** [swup/swup#256]
Hello,

I've created a responsive navbar with internal links inside. When you click on these links, the swup animation runs smoothly, but the JQuery script used to detect the opening of the menu in mobile mode doesn't work anymore. Basically, the menu doesn't open anymore once you change page. 
I tried to search on Google but I couldn't find anything. So I hope to find my answer here. 

I use the framework Symfony. 
My base.html.twig:
```twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta name="description" content="">
    <title>{% block title %}Clément OZOR - Développeur Web{% endblock %}</title>
    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <!-- HAMBURGERS.CSS -->
    <link rel="stylesheet" href="{{ asset('css/hamburgers.min.css') }}">
    <!-- ANIMATE.CSS -->
    <link rel="stylesheet" href="{{ asset('css/animate.min.css') }}">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ asset('css/common.css') }}">
    {% block stylesheets %}{% endblock %}
</head>
<body>
    <!-- BACKGROUND -->
    <div class="bg-particles"></div>
    <!-- PAGE -->
    <div id="swup">
        <div class="header">
            {% include "includes/nav.html.twig" %}
        </div>
        <div class="body transition-fade">
            {% block body %}{% endblock %}
        </div>
        <div class="footer">
            {% include "includes/footer.html.twig" %}
        </div>
    </div>
    <!-- JQUERY -->
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <!-- SWUP.JS -->
    <script src="{{ asset('js/swup.min.js') }}"></script>
    <!-- PARTICLEGROUND -->
    <script src="{{ asset('js/jquery.particleground.min.js')}}"></script>
    <!-- SCRIPT -->
    <script src="{{ asset('js/app.js') }}"></script>
    {% block javascripts %}{% endblock %}
</body>
</html>```

nav.html.twig:
```twig
<header>
    <nav>
        <ul>
            <div class="left">
                <li><a href="{{ path('home') }}" class="navbar-title navbar-link-animation">ModzDev_</a></li>
            </div>
            <div class="right">
                <div class="bg-mobile"></div>
                <li><a href="{{ path('home') }}" class="navbar-link-animation {% if page_name == 'home' %}active{% endif %}">Accueil</a></li>
                <li><a href="{{ path('about') }}" class="navbar-link-animation {% if page_name == 'about' %}active{% endif %}">A propos</a></li>
                <li><a href="#" class="navbar-link-animation">Blog</a></li>
                <li><a href="#" class="navbar-link-animation">Contact</a></li>
            </div>
            <button class="hamburger hamburger--spring" type="button">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </ul>
    </nav>
</header>
```

common.css:
```css
@import url('https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap');

/* 
    DEFAULT 
*/
* {
    padding: 0;
    margin: 0;
    font-family: 'Poppins', sans-serif;
    position: relative;
}

body {
    width: 100vw;
    min-height: 100vh;
    background-color: #2d3436;
    overflow-x: hidden;
}

.bg-particles {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    background: rgb(0, 116, 255);
    background: -moz-linear-gradient(45deg, rgba(0, 116, 255, 0.4) 0%, rgba(230, 36, 225, 0.4) 100%);
    background: -webkit-linear-gradient(45deg, rgba(0, 116, 255, 0.4) 0%, rgba(230, 36, 225, 0.4) 100%);
    background: linear-gradient(45deg, rgba(0, 116, 255, 0.4) 0%, rgba(230, 36, 225, 0.4) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#0074ff", endColorstr="#e624e1", GradientType=1);
    z-index: -1;
}

#swup {
    min-height:100vh;
	display:flex;
	flex-direction:column;
}

.body {
    flex-grow: 1;
    padding-top: 100px;
}

/* 
    NAVBAR
*/
header {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100px;
    z-index: 999999;
}

header nav {
    position: relative;
    width: inherit;
    height: inherit;
}

header nav ul {
    height: inherit;
    list-style: none;
    display: flex;
    justify-content: space-between;
    margin: 0 50px;
}

header nav ul div {
    height: inherit;
    display: flex;
    align-items: center;
}

header nav a.navbar-title {
    font-weight: 700;
    font-size: larger;
}

header nav a,
header nav a:visited {
    display: inline-block;
    padding: 20px 30px;
    text-decoration: none;
    color: #fff;
    position: relative;
    overflow: hidden;
}

header nav a.navbar-link-animation::before {
    content: '';
    position: absolute;
    top: 0;
    left: -101%;
    width: 100%;
    height: 50%;
    background: rgba(223, 230, 233, .3);
    transition: .4s;
    z-index: -1;
}

header nav a.navbar-link-animation::after {
    content: '';
    position: absolute;
    bottom: 0;
    right: -101%;
    width: 100%;
    height: 50%;
    background: rgba(223, 230, 233, .3);
    transition: .4s;
    z-index: -1;
}

header nav a.navbar-link-animation:hover::before {
    left: 0;
    transition: .4s;
}

header nav a.navbar-link-animation:hover::after {
    right: 0;
    transition: .4s;
}

header nav a.navbar-link-animation.active {
    background: rgba(223, 230, 233, .3);
}

header nav a.navbar-link-animation.active:hover::before,
header nav a.navbar-link-animation.active:hover::after {
    display: none;
}

/* HAMBURGER */
header nav .hamburger {
    display: none;
}

header nav .hamburger:focus,
header nav .hamburger::selection {
    outline: none;
}

header nav .hamburger:hover,
header nav .hamburger.is-active:hover {
    opacity: 1;
}

header nav .hamburger--spring .hamburger-inner,
header nav .hamburger--spring .hamburger-inner:after,
header nav .hamburger--spring .hamburger-inner:before {
    background-color: #fff !important;
}

header nav .hamburger--spring.is-active .hamburger-inner:before,
header nav .hamburger--spring.is-active .hamburger-inner:after {
    background-color: #fff !important;
}


/* 
    FOOTER
*/
footer {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100px;
}

footer p {
    text-align: center;
    color: #fff;
    font-size: 14pt;
}


/* 
    For separate header and body
*/




/* 
    RESPONSIVE
*/

@media (max-width: 991.98px) {

    /* NAVBAR */
    header nav ul {
        margin: 0;
    }

    header nav .right {
        position: absolute;
        width: 100vw;
        height: 0;
        flex-direction: column;
        justify-content: center;
        top: 100%;
        overflow: hidden;
        transition:  0.5s;
    }

    header nav .right.navbar-visible {
        height: calc(100vh - 100px);
        transition:  0.5s;
    }

    header nav .bg-mobile {
        width: inherit;
        height: inherit;
        background: rgba(255, 255, 255, 0.8);
        position: absolute;
        top: 0;
    }

    header nav .right a {
        color: #2d3436;
    }

    /* HAMBURGER */
    header nav .hamburger {
        display: block;
    }
}


/* 
    SWUP
*/
.transition-fade {
    transition: 0.4s;
    opacity: 1;
}

html.is-animating .transition-fade {
    opacity: 0;
}
```

app.js: 
```js 
const swup = new Swup();


$(document).ready(function () {
    // Particleground
    $('.bg-particles').particleground({
        dotColor: 'rgba(255, 255, 255, 0.7)',
        lineColor: 'rgba(255, 255, 255, 0)',
        minSpeedX: 0.1,
        maxSpeedX: 0.5,
        minSpeedY: 0.1,
        maxSpeedY: 0.5,
        density: 15000,
        curvedLines: false,
        proximity: 20,
        parallaxMultiplier: 5,
        particleRadius: 5,
    });

    // Hamburger toggle
    $('.hamburger').on('click', function() {
        alert('Click');
        $(this).toggleClass('is-active');
        $('header nav .right').toggleClass('navbar-visible');
        $('header nav a').toggleClass('navbar-link-animation');
    });
});
```

Thank you in advance.
