### ISSUE TITLE
How to remove the fade-out transition?

### ISSUE THREAD

**Issue by artware-vagos** [swup/swup#297]
Hello,

I am building this transition. Please click the image on the page to see it.
http://artware.gr/swup/

How can I remove the "in-between" fadeOut effect?
Is this possible?

Thank you!

**Comment by AugustMiller** [comment]
Looks like you've got some CSS that is applying opacity transitions. Remove that, and your page should remain visible during navigation.

Lines 151-159, in `style.css`:
```css
/*** SWUP ***/
main.transition-fade {
  transition: .4s;
  opacity: 1;
}

html.is-animating main.transition-fade {
  opacity: 0;
}
```
