### ISSUE TITLE
Swup not working with keyframes

### ISSUE THREAD

**Issue by obj-obj** [swup/swup#312]
I've been trying to fix this issue for a while, and it's a simple one.
My problem is that whenever I add an animation that uses keyframes to my transition class, swup stops replacing the content of the page when a link is clicked.
If I use regular attributes such as opacity, the content of the page is replaced correctly.
Does anyone know how to fix this problem?

**Comment by daun** [comment]
swup listens to `transitions`, not `animations`.

For anything with keyframes, you'll most likely have to animate the elements in JS.

**Comment by obj-obj** [comment]
Ah, so it won't ever work with keyframes
I was thinking that if I set the transition value to the length of the animation it would automatically wait for the correct time, lol

**Comment by daun** [comment]
You might be onto something there. Never tried it, but it could work if you're transitioning a different property from the one you're animating.

**Comment by obj-obj** [comment]
Well this is kinda hacky, but it works :D
```css
.transition-slide {
    transition: 1s;
    animation: slidein 1s ease-in-out;
    opacity: 1;
}

html.is-animating .transition-slide {
    animation: slideout 1s ease-in-out;
    opacity: 0;
}
```
