### ISSUE TITLE
Not waiting for transition to complete on Chrome

### ISSUE THREAD

**Issue by connellmccarthy** [swup/swup#409]
**Describe your issue**:
Weirdly enough swup stopped waiting for the transition to complete when browsing on Chrome. It works when navigating back to the homepage, but any other page it doesn't wait. It still works as expected in Safari, Safari mobile, and Firefox though. Any ideas on where to begin figuring out what's going on will be a huge help.

**Swup config or any additional relevant code used**:

```javascript
const swup = new Swup({
  plugins: [new SwupSlideTheme(),new SwupDebugPlugin()]
});
init();

swup.on('contentReplaced', init);
```

```scss
.swup-transition-main {
  opacity: 1;
  transition: opacity 0.3s, transform 0.4s;
  transform: translate3d(0, 0, 0);
}

html {
	&.is-animating {
		.swup-transition-main {
			opacity: 0;
			transform: translate3d(0, 30px, 0);
		}
		&.is-leaving {
			.swup-transition-main {
				opacity: 0;
				transform: translate3d(0, -30px, 0);
			}
		}
		&.swup-theme-reverse {
			.swup-transition-main {
				opacity: 0;
				transform: translate3d(0, -30px, 0);
			}
			&.is-leaving {
				.swup-transition-main {
					opacity: 0;
					transform: translate3d(0, 30px, 0);
				}
			}
		}
	}
}
```

Examples:

**Safari**
https://user-images.githubusercontent.com/10442875/149043692-b48df906-2e31-4b09-95a4-d0f41ef2bbdf.mp4

**Chrome**
Version 97.0.4692.71 (Official Build) (x86_64)
https://user-images.githubusercontent.com/10442875/149043758-00987168-cbe1-4f94-b7b0-4ba7fed29831.mp4
