### ISSUE TITLE
Full page menu isn't finishing animation

### ISSUE THREAD

**Issue by abstractTechnica** [swup/swup#411]
I'm using a function to call menu file for a full screen menu as such:

```html
<script> 
	$(function(){
		$("#menu").load("menu.html");
	});
</script>
```

```html
<div class="menu-overlay">
	<input type="checkbox" class="toggler">
	<div class="menu-button"><div></div></div>
	<div class="nav">
		<div>
			<div>
				<div id="menu"></div>
			</div>
		</div>
	</div>
</div>
```

The code for swup is in the menu html file as follows:

```html
<main id="swup" class="transition-wipe">
	<ul>
		<li><a href="/index.html">philosophy</a></li>
		<li><a href="#">services</a></li>
		<li><a href="/contact.html">contact </a></li>
	</ul>
</main>
```

it sort of works. From what I can see, the animation is happening much quicker than what is set by transition and then loads the next page. Currently, the full screen menu drops down over the screen using CSS. I have been trying to trouble shoot and see if the CSS is conflicting with the swup but can't figure it out.

Here's the CSS:

```css
.menu-overlay .toggler:checked ~ .nav {
	visibility: visible;
	}

.menu-overlay .toggler:checked ~ .nav > div{
	transform: scale(1);
	transition-duration: 1s ease;
	}

.menu-overlay .toggler:checked ~ .nav > div > div{
	opacity: 1;
	transition: opacity 1s ease;
	}

/*Menu overlay size and location settings*/
.menu-overlay .nav {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	visibility: hidden; 
	overflow: hidden;
	display: flex;
	align-items: center;
	justify-content: center;
	}

/*Menu overlay background settings*/
.menu-overlay .nav > div {
	background: var(--taupe-color);
	opacity: 0.95;
	width: 200vw;
	height: 200vw;
	display: flex;
	flex: none;
	align-items: center;
	justify-content: center;
	transform: translateY(-100%);
	transition: 3s;
	}

.transition-wipe {
	transition: 3s;
	transform: translateY(0);
	}
	
html.is-animating .transition-wipe {
	transform: translateY(100vh);
	}
```

Is this a swup issue? or a CSS issue? thanks
