### ISSUE TITLE
Make `animationSelector` pluggable

### ISSUE THREAD

**Issue by hirasso** [swup/swup#711]
**Describe the problem**

As [described here](https://github.com/swup/fragment-plugin/issues/8#issuecomment-1624912383), there are cases where it poses problems that swup always waits for the longest transition duration of elements matching `animationSelector`.

**Describe the proposed solution**

swup should provide a way to overwrite the `animationSelector` in the current `context` of a visit:

```js
swup.hooks.on("transitionStart", (context) => {
  if (isFragmentVisit(context)) {
    context.transition.selector = "#list, #other-fragment";
  }
});
```

Animations for fragments could then be scoped to the fragments like this:

```css
#list {
  transition-property: opacity;
  transition-duration: 200ms;
}

#list.is-animating {
  opacity: 0;
}
```
If the children of a fragment should be animated, the full duration of the animation should be defined on the fragment itself, like this:

```css
#list {
  transition-duration: 200ms;
}

.list_item {
  transition-property: opacity, transform;
  transition-duration: 200ms;
}

#list.is-animating .list_item {
  opacity: 0;
  transform: scale(0.75);
}
```

**How important is this feature to you?**

- [x] This is the only way I see right now to introduce the fragment plugin without any breaking changes to swup and the themes
